# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='\u89d2\u8272\u7f16\u53f7')),
                ('role_name', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('extra', models.CharField(max_length=128, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'role',
                'verbose_name': '\u89d2\u8272\u8868',
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.CreateModel(
            name='RoleMappingView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u5217\u53f7')),
                ('role_id', models.IntegerField(verbose_name='\u89d2\u8272\u7f16\u53f7')),
                ('view_id', models.CharField(max_length=32, verbose_name='\u89c6\u56fe\u7f16\u53f7')),
            ],
            options={
                'db_table': 'role_mapping_view',
                'verbose_name': '\u89d2\u8272\u89c6\u56fe\u5173\u7cfb\u8868',
                'verbose_name_plural': '\u89d2\u8272\u89c6\u56fe\u5173\u7cfb\u8868',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u89c6\u56fe\u7f16\u53f7')),
                ('parent_view_id', models.IntegerField(verbose_name='\u7236\u7ea7\u7f16\u53f7')),
                ('view_url', models.CharField(max_length=128, verbose_name='URL\u5bfc\u822a\u5730\u5740')),
                ('view_name', models.CharField(max_length=32, verbose_name='URL\u5bfc\u822a\u540d\u79f0')),
                ('extra', models.CharField(max_length=128, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'view',
                'verbose_name': '\u89c6\u56fe\u8868',
                'verbose_name_plural': '\u89c6\u56fe\u8868',
            },
        ),
    ]
